# Generated by Django 3.2.10 on 2021-12-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=100)),
            ],
        ),
    ]
